### PR TITLE
add Ukrainian locale

### PR DESCRIPTION
**Pull request by globart**
## Pull Request template

Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:

   a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feat/` prefixes. Good examples are: `fix/signin-issue` or `feat/issue-templates`.

   b. You have a descriptive commit message with a short title (first line).

   c. You have only one commit (if not, squash them into one commit).

   d. Make sure `yarn lint` & `yarn format` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).

3. **After** these steps, you're ready to open a pull request.

   a. Give a descriptive title to your PR.

   b. Provide a description of your changes.

   c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.

**PLEASE REMOVE THIS TEMPLATE BEFORE SUBMITTING**

### CODE REVIEW

**Comment by globart** [comment]
@cherrybarry Please review and merge, I've already submitted the locale itself and it got merged to master - https://github.com/Nearblocks/translations/pull/48

**Comment by andrewklau** [comment]
You'll need to update the package here to the latest commit https://github.com/Nearblocks/nearblocks/blob/main/apps/app/package.json#L44 and then the lock file

**Comment by globart** [comment]
@andrewklau done

**Comment by andrewklau** [comment]
thanks @globart !

**Comment by globart** [comment]
@andrewklau does it have to be deployed somehow? Because I don't see the option for Ukrainian on the website

**Comment by andrewklau** [comment]
should be here now https://nearblocks.io/ua

**Comment by globart** [comment]
@andrewklau I see it now, thanks!

**Pull request merged**
