### PR TITLE
feat(app): add ssr in home page stats and latest blocks and transactions

### PR DESCRIPTION
**Pull request by yudhomax**

### CODE REVIEW

**Review by cherrybarry — APPROVED** [review]

**Review by cherrybarry — APPROVED** [review]

**Comment by yudhomax** [comment]
@race-of-sloths

**Comment by race-of-sloths** [comment]
🥁  __Score it!__

@andrewklau, please score the PR with `@race-of-sloths score [1/2/3/5/8/13]`. The contributor deserves it.
If no scoring is provided within 24 hours, this PR will be scored as 2 🦥

**Comment by frol** [comment]
@race-of-sloths score 13

**Comment by andrewklau** [comment]
@race-of-sloths score 8

**Comment by race-of-sloths** [comment]
### ⏰️ Scoring closed
24 hours have already passed since the merge

**Pull request merged**
